/*
	A CONTINUACION LOS QUERYS PARA LA CREACIÓN DE LAS TABLAS.
*/

DROP TABLE IF EXISTS CUBO;
CREATE TABLE CUBO(
	IDENTIFICADOR INTEGER AUTO_INCREMENT,
    NUMERO INTEGER,
    COLOR VARCHAR(100),
    IDCARA INTEGER,
    PRIMARY KEY(IDENTIFICADOR)
);

/*
	A CONTINUACION LOS QUERYS PARA EL LLENADO DE LAS TABLAS.
*/

DROP PROCEDURE IF EXISTS INICIALIZAR_COLORES;
DELIMITER $$
CREATE PROCEDURE INICIALIZAR_COLORES()
BEGIN
	INSERT INTO CUBO VALUES(DEFAULT, 0, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "blanco", 0);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "blanco", 0);

	INSERT INTO CUBO VALUES(DEFAULT, 0, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "amarillo", 1);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "amarillo", 1);

	INSERT INTO CUBO VALUES(DEFAULT, 0, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "azul", 2);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "azul", 2);

	INSERT INTO CUBO VALUES(DEFAULT, 0, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "rojo", 3);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "rojo", 3);

	INSERT INTO CUBO VALUES(DEFAULT, 0, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "verde", 4);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "verde", 4);

	INSERT INTO CUBO VALUES(DEFAULT, 0, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 1, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 2, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 3, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 4, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 5, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 6, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 7, "naranja", 5);
	INSERT INTO CUBO VALUES(DEFAULT, 8, "naranja", 5);
END$$
DELIMITER ;



DROP PROCEDURE IF EXISTS REINICIAR_COLORES;
DELIMITER $$
CREATE PROCEDURE REINICIAR_COLORES()
BEGIN
TRUNCATE TABLE CUBO;
END$$
DELIMITER ;REINICIAR_COLORES

DROP PROCEDURE IF EXISTS ACTUALIZAR_CUADRO;
DELIMITER $$
CREATE PROCEDURE ACTUALIZAR_CUADRO(COLOR_P VARCHAR(100),NUMERO_P INTEGER, IDCARA_P INTEGER)
BEGIN
	UPDATE CUBO SET COLOR=COLOR_P WHERE NUMERO=NUMERO_P AND IDCARA=IDCARA_P;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA0;
DELIMITER $$
CREATE PROCEDURE LEER_CARA0()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=0; 
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA1;
DELIMITER $$
CREATE PROCEDURE LEER_CARA1()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=1;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA2;
DELIMITER $$
CREATE PROCEDURE LEER_CARA2()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=2;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA3;
DELIMITER $$
CREATE PROCEDURE LEER_CARA3()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=3;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA4;
DELIMITER $$
CREATE PROCEDURE LEER_CARA4()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=4;
END$$
DELIMITER ;

DROP PROCEDURE IF EXISTS LEER_CARA5;
DELIMITER $$
CREATE PROCEDURE LEER_CARA5()
BEGIN
	SELECT NUMERO, COLOR FROM CUBO WHERE IDCARA=5;
END$$
DELIMITER ;


SELECT * FROM CUBO;
SELECT * FROM CUBO WHERE IDCARA=0;


UPDATE CUBO SET COLOR='blanco' WHERE NUMERO=1 AND IDCARA=0;

SET SQL_SAFE_UPDATES = 0;